version: '2'
services:

  zookeeper:
    image: biggis/zookeeper:3.4.6
    restart: always
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      USER_ID: ${USER_ID}
      USER_NAME: zookeeper
    volumes:
      - zookeeper-data:/tmp/zookeeper/data

  kafka:
    image: biggis/kafka:0.9.0.0
    restart: always
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: w-stcs-services
      USER_ID: ${USER_ID}
      USER_NAME: kafka
    volumes:
      - kafka-data:/tmp/kafka/data

  postgres:
    image: biggis/postgres:9.6-alpine
    restart: always
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: stcsdb
      POSTGRES_USER: postgres
      POSTGRES_PW: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg-data:/var/lib/postgresql/data/pgdata

  pgadmin:
    image: fenglc/pgadmin4:1.0
    restart: always
    hostname: pgadmin4
    ports:
      - "80:5050"

volumes:
  zookeeper-data:
  kafka-data:
  pg-data:
